#! /usr/bin/env bash
set -Eeuo pipefail

function usage() {
  echo "Usage:"
  echo "  $0 <ENV>"
  echo "  ENV: Environment to clean snapshot of (e.g. tst)"
}

if [[ $# != 1 ]]; then
  usage
  exit 1
fi

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

instance="$1"
if ccontrol qlist "$instance" &> /dev/null; then # Make sure instance is valid
  lv_name=$(lvs | grep ${instance}_snap) | awk '{ print $1 }'
  if (set -f ; IFS=$'\n'; set -- x${lv_name}x ; [ $# = 1 ]) ; then
    echo "ERROR: More than one LV returned"
    exit 2
  fi
else
  echo "ERROR - Can't find instance ${instance}."
  exit 2
fi

if ! lvs "$lv_name" &> /dev/null; then
  echo "ERROR - $lv_name does not appear to be a LVM logical volume."
  exit 2
fi

vg=$(lvs --noheadings -o vg_name "$lv_name" | sed 's/ //g')

lv_path="/dev/mapper/${vg}-${lv_name}"

mount_points=$(mount | grep $lv_path | awk '{ print $3 }')

for mount_point in $mount_points; do
  umount $mount_point
  rmdir $mount_point
done

lvremove -f "/dev/mapper/${vg}-${lv_name}"

# vim:set ts=2 sw=2 et:
