#! /usr/bin/env bash

nojournal='^dcifc$|^eid$|^err$|^loc$|^locmu$|^rt$|^rtepicsec$|^rtlimited$|^rtrouscratch$|^rtrouscratchlimited$|^scratchdb$'

function usage() {
	echo "Usage:"
	echo "  $0 <SRC> <DST>"
	echo "  SRC: Path to source environment (e.g. /epic/mst)"
	echo "  DST: Path to desitnation environment"
}

if [[ $# != 2 ]]; then
	usage
	exit 1
fi

src="${1}"
dst="${2}"

if [[ ! -d $src ]] || [[ ! -d $dst ]]; then
	usage
	exit 2
fi

cd $src
for ds in $(find * -maxdepth 1 -type f \( -name CACHE.DAT -o -name IRIS.DAT \) 2> /dev/null | egrep -v "$nojournal"); do # Find all journaled data sets for the instance
	echo "$ds" | cut -d '/' -f 1
	mkdir -p "${dst}/$(find $ds -printf "%h\n")"
	pv "${ds}" > "${dst}/${ds}"
done